version: '3.8'
services:

  db:
    image: mysql/mysql-server:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - 'parking_volume:/var/lib/mysql'

  backend:
    image: kreamsandwich/parking_backend:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/backend/static/
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
    depends_on:
      - backend
      - db
    env_file:
      ./.env

volumes:
  static_volume:
  parking_volume:
