version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data_volume:/var/lib/postgresql/data

  backend:
    platform: linux/amd64
    build:
      context: ../.
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/backend/static/
      - media_volume:/backend/media/
      - shared_data:/backend/parser
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    platform: linux/amd64
    image: parkonaft/client:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./local.nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend
      - db
      - frontend
    env_file:
      - ./.env

  # parser:
  #  build:
  #    context: ../parser
  #    dockerfile: Dockerfile
  #  depends_on:
  #    - backend
  #    - db
  #  volumes:
  #    - shared_data:/parser
  #  env_file:
  #    - ./.env

volumes:
  static_volume:
  media_volume:
  pg_data_volume:
  shared_data:
