version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data_volume:/var/lib/postgresql/data

  backend:
    image: parkonaft/server:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/backend/static/
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    image: parkonaft/client:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./local.nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
    depends_on:
      - backend
      - db
      - frontend
    env_file:
      ./.env

volumes:
  static_volume:
  pg_data_volume:
