# Generated by Django 4.2.3 on 2023-08-12 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес парковки')),
                ('latitude', models.FloatField(max_length=40, verbose_name='Координаты x')),
                ('longitude', models.FloatField(max_length=40, verbose_name='Координаты y')),
                ('car_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Количество парковочных мест не может быть меньше одного')], verbose_name='Общее количество парковочных мест')),
                ('tariffs', models.CharField(max_length=2500, verbose_name='Стоимость парковки')),
            ],
            options={
                'verbose_name': 'Парковка',
                'verbose_name_plural': 'Парковки',
            },
        ),
    ]
