# Generated by Django 4.2.3 on 2023-08-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='coordinates_x',
            field=models.CharField(default=1, max_length=40, unique=True, verbose_name='Координаты x'),
            preserve_default=False,
        ),
    ]
