# Generated by Django 4.2.3 on 2023-09-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='parking_lots/logos/', verbose_name='Лого')),
                ('email', models.CharField(max_length=100, verbose_name='Адрес электронной почты')),
                ('about', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О продукте',
                'verbose_name_plural': 'О продукте',
            },
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='latitude',
            field=models.FloatField(max_length=40, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='longitude',
            field=models.FloatField(max_length=40, verbose_name='Долгота'),
        ),
    ]
