# Generated by Django 4.2.3 on 2023-09-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='latitude',
            field=models.FloatField(max_length=40, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='longitude',
            field=models.FloatField(max_length=40, verbose_name='Долгота'),
        ),
    ]
