# Generated by Django 4.2.3 on 2023-08-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0002_remove_parkinglot_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='coordinates_y',
            field=models.FloatField(default=1, max_length=40, unique=True, verbose_name='Координаты y'),
            preserve_default=False,
        ),
    ]
