# Generated by Django 4.2.3 on 2023-08-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0003_parkinglot_coordinates_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='object_type',
        ),
    ]
