# Generated by Django 4.2.3 on 2023-08-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0004_remove_parkinglot_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='coordinates_x',
            field=models.FloatField(max_length=40, unique=True, verbose_name='Координаты x'),
        ),
    ]
