# Generated by Django 4.2.3 on 2023-08-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0005_alter_parkinglot_coordinates_x'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinglot',
            old_name='coordinates_x',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='parkinglot',
            old_name='coordinates_y',
            new_name='longitude',
        ),
    ]
