# Generated by Django 4.2.3 on 2023-08-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0006_rename_coordinates_x_parkinglot_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='latitude',
            field=models.FloatField(max_length=40, verbose_name='Координаты x'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='longitude',
            field=models.FloatField(max_length=40, verbose_name='Координаты y'),
        ),
    ]
