name: Push to dockerhub & deploy
on:
  push:
    branches:
      - develop
    paths-ignore:
      - "*/README.md"

jobs:  
  push_to_dockerhub:
    name: Push backend image to Dockerhub
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1 
    - name: Login to Docker 
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2 
      with:
          push: true
          tags: parkonaft/server:latest
      
  
  deploy:
    runs-on: ubuntu-latest
    needs: push_to_dockerhub
    
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.HOST_USER }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            cd ../home/backend/infra/
            sudo docker compose down --rmi local
            sudo docker pull parkonaft/server:latest
            sudo docker compose up --build -d
